import { loadNetlist } from "../load-netlist.js";
import { isTestpoint, naturalSort } from "../../circuit-traversal.js";
import { isAutoGeneratedNetName } from "../../net-categories.js";
import {
  isErrorResult,
  type NetConnections,
  type ComponentDetails,
  type ErrorResult,
} from "../../types.js";

export type Severity = "error" | "warning";

export interface ErcOptions {
  includeDns?: boolean;
  includeRules?: string[];
  excludeRules?: string[];
}

export interface ErcResult {
  design: string;
  checked: string[];
  skipped?: Record<string, number>;
  // Every value is { [net]: endpoints[] } EXCEPT net.unnamed, whose value is a
  // bare net-name string[] (it has no endpoints). That one key is why these are
  // unions rather than Record<string, Record<string, string[]>>.
  errors?: Record<string, Record<string, string[]> | string[]>;
  warnings?: Record<string, Record<string, string[]> | string[]>;
}

/** Per-net endpoints split by kind, computed once and shared by every rule. */
interface NetScan {
  functional: string[]; // "REFDES.PIN" for non-testpoint pins
  testpoints: string[]; // "REFDES.PIN" for TP* pins
}

interface RuleFinding {
  net: string;
  endpoints?: string[]; // omitted for net.unnamed (bare net-name list)
}

interface Rule {
  id: string;
  severity: Severity;
  shape: "map" | "arr"; // "arr" → bare net[]; "map" → { [net]: endpoints[] }
  run: (scan: Map<string, NetScan>) => RuleFinding[];
}

const collect = (
  scan: Map<string, NetScan>,
  match: (net: string, s: NetScan) => boolean,
  endpoints: (s: NetScan) => string[] | undefined
): RuleFinding[] =>
  [...scan.entries()]
    .filter(([net, s]) => match(net, s))
    .map(([net, s]) => ({ net, endpoints: endpoints(s)?.slice().sort(naturalSort) }));

// R = functional pin count, T = testpoint pin count. The three degenerate rules
// are mutually exclusive (R/T buckets don't overlap); net.unnamed's R>=2 guard
// keeps it from doubling up on a net already flagged by single_pin/orphan/stub.
const RULES: Rule[] = [
  {
    id: "net.single_pin",
    severity: "error",
    shape: "map",
    run: (scan) =>
      collect(
        scan,
        (_net, s) => s.functional.length === 1 && s.testpoints.length === 0,
        (s) => s.functional
      ),
  },
  {
    id: "net.testpoint_orphan",
    severity: "error",
    shape: "map",
    run: (scan) =>
      collect(
        scan,
        (_net, s) => s.functional.length === 0 && s.testpoints.length >= 1,
        (s) => s.testpoints
      ),
  },
  {
    id: "net.testpoint_stub",
    severity: "warning",
    shape: "map",
    run: (scan) =>
      collect(
        scan,
        (_net, s) => s.functional.length === 1 && s.testpoints.length >= 1,
        (s) => [...s.functional, ...s.testpoints]
      ),
  },
  {
    id: "net.unnamed",
    severity: "warning",
    shape: "arr",
    run: (scan) =>
      collect(
        scan,
        (net, s) => s.functional.length >= 2 && isAutoGeneratedNetName(net),
        () => undefined
      ),
  },
];

const buildScan = (
  nets: NetConnections,
  components: ComponentDetails,
  includeDns: boolean
): { scan: Map<string, NetScan>; skippedDns: number } => {
  const scan = new Map<string, NetScan>();
  const skippedDns = new Set<string>();
  for (const [net, conns] of Object.entries(nets)) {
    if (net === "NC") continue; // normalized no-connect placeholder, not a real net
    const functional: string[] = [];
    const testpoints: string[] = [];
    for (const [refdes, pins] of Object.entries(conns)) {
      if (!includeDns && components[refdes]?.dns) {
        skippedDns.add(refdes);
        continue;
      }
      const bucket = isTestpoint(refdes) ? testpoints : functional;
      for (const pin of pins) bucket.push(`${refdes}.${pin}`);
    }
    scan.set(net, { functional, testpoints });
  }
  return { scan, skippedDns: skippedDns.size };
};

/**
 * Run electrical rule checks over a design's netlist. Full output, never truncated.
 */
export const runErc = async (
  design: string,
  opts: ErcOptions = {}
): Promise<ErcResult | ErrorResult> => {
  const netlist = await loadNetlist(design);
  if (isErrorResult(netlist)) return netlist;

  const includeDns = opts.includeDns ?? false;
  const { scan, skippedDns } = buildScan(netlist.nets, netlist.components, includeDns);

  const inc = opts.includeRules;
  const exc = new Set(opts.excludeRules ?? []);

  // An explicit empty include_rules is ambiguous (run all? run none?) and either
  // silent choice misleads: "run none" reads as a clean design, "run all" defies a
  // deliberate empty selection. Refuse to guess; omitting the field already means all.
  if (inc && inc.length === 0) {
    return { error: "include_rules was empty. Omit it to run all rules, or list the rule ids to run." };
  }

  // Reject typo'd rule ids: otherwise include_rules: ["net.singel_pin"] yields
  // checked: [] with no findings, which an agent reads as "design is clean".
  const known = new Set(RULES.map((r) => r.id));
  const unknown = [...(inc ?? []), ...exc].filter((id) => !known.has(id));
  if (unknown.length > 0) {
    return { error: `Unknown rule id(s): ${unknown.join(", ")}. Valid ids: ${[...known].join(", ")}` };
  }

  const selected = RULES.filter((r) => (!inc || inc.includes(r.id)) && !exc.has(r.id));

  const errors: Record<string, Record<string, string[]> | string[]> = {};
  const warnings: Record<string, Record<string, string[]> | string[]> = {};
  for (const rule of selected) {
    const findings = rule.run(scan);
    if (findings.length === 0) continue;
    const bucket = rule.severity === "error" ? errors : warnings;
    if (rule.shape === "arr") {
      bucket[rule.id] = findings.map((f) => f.net).sort(naturalSort);
    } else {
      // Endpoint lists are ALWAYS arrays here, even at length 1. Do not "simplify"
      // single-element endpoints to a bare string; the ERC contract is uniform arrays.
      const map: Record<string, string[]> = {};
      for (const f of [...findings].sort((a, b) => naturalSort(a.net, b.net))) {
        map[f.net] = f.endpoints ?? [];
      }
      bucket[rule.id] = map;
    }
  }

  const result: ErcResult = { design, checked: selected.map((r) => r.id) };
  if (Object.keys(errors).length > 0) result.errors = errors;
  if (Object.keys(warnings).length > 0) result.warnings = warnings;
  if (!includeDns && skippedDns > 0) result.skipped = { dns: skippedDns };
  return result;
};
