/**
 * Variant Do Not Stuff, measured against a board's own BOM.
 *
 * LAUNCHXL-CC1310 ships `LAUNCHXL-CC1310_1_3_0_BOM.xlsx` beside the schematic,
 * generated by CIS from these very variants. Twenty-five of its part references
 * are written with Part Number `DNM` and Quantity 0, and those are the parts
 * below. None of them carries a DNS marker in its value, so the .dat parsers
 * see an ordinary part and the count answered before this was eleven, all of
 * them found by other means and all of them inside this set.
 *
 * The design keeps a netlist beside the schematic, so `list_designs` hands out
 * its `pstxnet.dat` and that is the path a query arrives with. Both paths are
 * asserted here because the flag has to survive the one that never opens the
 * schematic.
 */

import { describe, expect, it } from "vitest";
import { cadenceHandler } from "./index.js";
import { fixturePath, hasFixtures } from "../../../test/utils.js";

const CC1310 = ["cadence", "LAUNCHXL-CC1310", "doc", "hardware", "cc1310", "launchpad"];

const DSN = fixturePath(...CC1310, "design_files", "Cadence", "LAUNCHXL-CC1310.DSN");
const PSTXNET = fixturePath(...CC1310, "design_files", "Cadence", "Allegro", "pstxnet.dat");

/** Every part the CIS BOM writes as `DNM` with Quantity 0. */
const BOM_DO_NOT_STUFF = [
  "A1",
  "C24",
  "C58",
  "FIDU1",
  "FIDU2",
  "FIDU3",
  "FIDU4",
  "FIDU5",
  "FIDU6",
  "MH1",
  "MH2",
  "MH3",
  "MH4",
  "MH5",
  "P8",
  "R13",
  "R19",
  "R21",
  "R46",
  "R47",
  "R48",
  "R49",
  "R51",
  "R59",
  "R60",
];

const dnsRefdes = async (designPath: string): Promise<string[]> => {
  const parsed = await cadenceHandler.parse(designPath);
  return Object.entries(parsed.components)
    .filter(([, component]) => component.dns)
    .map(([refdes]) => refdes)
    .sort();
};

describe.skipIf(!hasFixtures)("variant Do Not Stuff", () => {
  it("reports the BOM's unstuffed parts for a query against the netlist", async () => {
    expect(await dnsRefdes(PSTXNET)).toEqual(BOM_DO_NOT_STUFF);
  });

  it("reports the same set for a query against the schematic", async () => {
    expect(await dnsRefdes(DSN)).toEqual(BOM_DO_NOT_STUFF);
  });

  it("leaves a design whose variant store is empty alone", async () => {
    // reComputer J401 carries the CIS storage with no group in it, which is what
    // a design that has never declared a variant writes.
    const design = fixturePath(
      "cadence",
      "OSHW-Jetson-Series",
      "reComputer Jetson carrier board",
      "reComputer J401",
      "Schematic",
      "reComputer J401_V1.0.DSN"
    );

    expect(await dnsRefdes(design)).toEqual([]);
  });
});
