import { describe, expect, it } from "vitest";
import { decryptSapphireII } from "./sapphire.js";
import vectors from "./sapphire-vectors.json" with { type: "json" };

// Synthetic known answers generated by an independent Python transcription of
// the OrCAD routine, not by an encryptor sharing the TypeScript implementation.
describe("OrCAD Sapphire II", () => {
  for (const [index, vector] of vectors.entries()) {
    it(`decrypts known answer ${index} without mutating inputs`, () => {
      const key = Buffer.from(vector.key, "hex");
      const cipher = Buffer.from(vector.cipher, "hex");
      const expected = Buffer.from(vector.plain, "hex");
      expect(Buffer.from(decryptSapphireII(cipher, key))).toEqual(expected);
      expect(Buffer.from(decryptSapphireII(cipher, key))).toEqual(expected);
      expect(key.toString("hex")).toBe(vector.key);
      expect(cipher.toString("hex")).toBe(vector.cipher);
    });
  }
  it("accepts empty payloads but rejects invalid key lengths", () => {
    expect(decryptSapphireII(new Uint8Array(), new Uint8Array([1]))).toHaveLength(0);
    for (const length of [0, 256]) {
      expect(() => decryptSapphireII(new Uint8Array(), new Uint8Array(length))).toThrow("1..255");
    }
  });
});
