import { describe, it, expect } from "vitest";
import { categorizeNet, isAutoGeneratedNetName } from "./net-categories.js";

describe("categorizeNet", () => {
  it.each([
    ["NC", "no-connect"],
    ["N12", "auto-generated"], // Cadence
    ["Net-(D1-A)", "auto-generated"], // KiCad named-by-pin
    ["unconnected-(J1-SBU1-PadA8)", "auto-generated"], // KiCad unconnected
    ["/Peripherals/Net-(D1-A)", "auto-generated"], // hierarchical: classified on final segment
    ["PP3V3", "named"],
    ["GND", "named"],
    ["USB_DP", "named"],
  ])("categorizes %s as %s", (name, expected) => {
    expect(categorizeNet(name)).toBe(expected);
  });

  it("isAutoGeneratedNetName is true only for auto-generated names", () => {
    expect(isAutoGeneratedNetName("Net-(R5-Pad2)")).toBe(true);
    expect(isAutoGeneratedNetName("N7")).toBe(true);
    expect(isAutoGeneratedNetName("VCC")).toBe(false);
    expect(isAutoGeneratedNetName("NC")).toBe(false);
  });
});
