/**
 * Net-name categorization shared across the app (DSN-vs-DAT coverage, ERC).
 *
 * Classifies a net by how its name was produced. Sheet-path-prefixed names
 * (e.g. KiCad's "/Sheet/Net-(D1-A)") are categorized on their final segment so
 * hierarchical nets categorize the same as flat ones.
 */

import { stripSheetPath } from "./circuit-traversal.js";

export type NetCategory = "no-connect" | "auto-generated" | "bus-range" | "named";

export const categorizeNet = (name: string): NetCategory => {
  const base = stripSheetPath(name);
  if (base === "NC") return "no-connect";
  if (/^N\d+$/.test(base)) return "auto-generated"; // Cadence
  if (/^Net-\(.*\)$/i.test(base)) return "auto-generated"; // KiCad named-by-pin
  if (/^unconnected-\(.*\)$/i.test(base)) return "auto-generated"; // KiCad unconnected
  if (/\[.*\.\.]/.test(base)) return "bus-range";
  return "named";
};

/** A net the tool auto-named (vs. a human-given label). */
export const isAutoGeneratedNetName = (name: string): boolean =>
  categorizeNet(name) === "auto-generated";
