import { describe, it, expect } from "vitest";
import { categorizeNet, isAutoGeneratedNetName } from "./net-categories.js";

describe("categorizeNet", () => {
  it.each([
    ["NC", "no-connect"],
    ["N12", "auto-generated"], // Cadence
    ["Net-(D1-A)", "auto-generated"], // KiCad named-by-pin
    ["unconnected-(J1-SBU1-PadA8)", "auto-generated"], // KiCad unconnected
    ["/Peripherals/Net-(D1-A)", "auto-generated"], // hierarchical: classified on final segment
    ["NetU9_A3", "auto-generated"], // Altium named-by-pin
    ["NetR182_1", "auto-generated"],
    ["NetDD12_AY1_1", "auto-generated"], // Altium, refdes expanded per channel
    ["NetIC49[_6", "auto-generated"], // Altium, channel 27 spelt past Z
    ["NetHTR_R8_2", "auto-generated"], // Altium, refdes with an underscore of its own
    ["NetU?_1", "auto-generated"], // Altium, unannotated part
    ["NetU1_VIN+", "auto-generated"], // Altium, pin designator with a sign
    ["UnnamedNet3", "auto-generated"],
    ["PP3V3", "named"],
    ["GND", "named"],
    ["USB_DP", "named"],
    ["NETWORK", "named"],
    ["Net_Enable", "named"],
    ["NetTie", "named"],
    ["NetTie_1", "named"], // hand-written: no number in the would-be refdes
    ["NetCtrl_EN", "named"],
    ["NetA_B", "named"],
  ])("categorizes %s as %s", (name, expected) => {
    expect(categorizeNet(name)).toBe(expected);
  });

  it("isAutoGeneratedNetName is true only for auto-generated names", () => {
    expect(isAutoGeneratedNetName("Net-(R5-Pad2)")).toBe(true);
    expect(isAutoGeneratedNetName("NetR9_2")).toBe(true);
    expect(isAutoGeneratedNetName("N7")).toBe(true);
    expect(isAutoGeneratedNetName("VCC")).toBe(false);
    expect(isAutoGeneratedNetName("NC")).toBe(false);
  });
});
